In [1]:
import matplotlib.pyplot as plt
import matplotlib
import mne
import pandas as pd
from utils import *

In [2]:
no()

[]


In [2]:
raw = mne.io.read_raw_bdf('error2.bdf')

Extracting EDF parameters from /Users/cindyzhang/Documents/M2/AM-piano/EEG/trig_tests/error2.bdf...
BDF file detected
Setting channel info structure...
Creating raw.info structure...


In [3]:
events = mne.find_events(raw, stim_channel='Status', shortest_event=1) #raises exception if shortest event is default 2...?

Trigger channel has a non-zero initial value of 130816 (consider using initial_event=True to detect this event)
1104 events found
Event IDs: [65282 65284 65288 65290]


In [16]:
import numpy as np

# Your array
my_array = np.array([
    [37726, 65280, 65288],
    [37729, 65280, 65288],
    [37733, 65280, 65288],
    [37735, 65280, 65288],
    [37739, 65280, 65288],
    [37746, 65280, 65288],
    [37753, 65280, 65288],
    [37757, 65280, 65288],
    [37764, 65280, 65288],
    [37783, 65280, 65288],
    [54111, 65282, 65288],
    [54119, 65280, 65288],
    [54123, 65280, 65288],
    [54130, 65280, 65288],
    [54152, 65280, 65288],
    [54159, 65280, 65288],
    [54166, 65280, 65288],
    [54213, 65280, 65288],
    [62302, 65280, 65288],
    [62311, 65280, 65288],
    [62315, 65280, 65288],
    [62321, 65280, 65288],
    [62329, 65280, 65288],
    [62339, 65280, 65288],
    [62347, 65280, 65288],
    [62405, 65280, 65288]
])

# Set the threshold for proximity between values in the first column
threshold = 100

# Calculate the difference between consecutive values in the first column
diff_first_column = np.diff(my_array[:, 0])

# Find the indices where the difference is greater than the threshold
indices = np.where(diff_first_column > threshold)[0]

# Include the first index to capture the first row
indices = np.concatenate(([0], indices + 1))

# Filter the array based on the indices
filtered_array = my_array[indices]

print(filtered_array)


[[37726 65280 65288]
 [54111 65282 65288]
 [62302 65280 65288]]


: 

In [9]:
diff_first_column

array([    3,     4,     2,     4,     7,     7,     4,     7,    19,
       16328,     8,     4,     7,    22,     7,     7,    47,  8089,
           9,     4,     6,     8,    10,     8,    58])